# Generated by Django 4.2.5 on 2023-09-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_home', '0002_auto_20230914_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacatoinHouse',
            new_name='VacatoinHome',
        ),
    ]
